/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting_uis;
import project1.*;


import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.awt.*;
import java.util.HashMap;
import java.util.Map;

import static project1.DistrictOffice.*;
import static project1.Pollingstation.*;
import static project1.Pollingstation.*;
import project1.ElectionsDemo.*;


/**
 *
 * @author Gideon Bonsu
 */
public class ResultsPage extends javax.swing.JFrame{


    /**
     * Creates new form ResultsPage
     */
    public ResultsPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {



        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        stationResults = new javax.swing.JButton();
        districtResults = new javax.swing.JButton();
        regionalResults = new javax.swing.JButton();
        nationalResults = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultsArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        stationResults.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        stationResults.setText("Station");
        stationResults.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stationResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationResultsActionPerformed(evt);
            }
        });

        districtResults.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        districtResults.setText("District");
        districtResults.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        districtResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                districtResultsActionPerformed(evt);
            }
        });

        regionalResults.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        regionalResults.setText("Regional");
        regionalResults.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        regionalResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionalResultsActionPerformed(evt);
            }
        });

        nationalResults.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        nationalResults.setText("National");
        nationalResults.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        nationalResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nationalResultsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(stationResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(districtResults, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(regionalResults, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                        .addComponent(nationalResults, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(stationResults, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(districtResults, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(regionalResults, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(nationalResults, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        resultsArea.setColumns(20);
        resultsArea.setRows(5);
        jScrollPane1.setViewportView(resultsArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(23, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(31, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Check Results Now!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(45, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void stationResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationResultsActionPerformed
        // TODO add your handling code here:
        resultsArea.append(ElectionsDemo.poll1.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll2.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll3.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll4.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll5.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll6.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll7.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll8.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll9.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll10.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll11.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll12.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll13.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll14.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll15.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll16.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll17.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll18.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll19.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.poll20.getLocation()+"\n"+String.valueOf(ElectionsDemo.poll1.collateResults())+"\n"+"\n");

        }
    //GEN-LAST:event_stationResultsActionPerformed

    private void districtResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_districtResultsActionPerformed
        // TODO add your handling code here:
        resultsArea.append(ElectionsDemo.district1.getLocation()+"\n"+String.valueOf(ElectionsDemo.district1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district2.getLocation()+"\n"+String.valueOf(ElectionsDemo.district2.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district3.getLocation()+"\n"+String.valueOf(ElectionsDemo.district3.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district4.getLocation()+"\n"+String.valueOf(ElectionsDemo.district4.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district5.getLocation()+"\n"+String.valueOf(ElectionsDemo.district4.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district6.getLocation()+"\n"+String.valueOf(ElectionsDemo.district1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district7.getLocation()+"\n"+String.valueOf(ElectionsDemo.district4.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district8.getLocation()+"\n"+String.valueOf(ElectionsDemo.district4.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district9.getLocation()+"\n"+String.valueOf(ElectionsDemo.district4.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.district10.getLocation()+"\n"+String.valueOf(ElectionsDemo.district4.collateResults())+"\n"+"\n");



    }//GEN-LAST:event_districtResultsActionPerformed

    private void regionalResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionalResultsActionPerformed
        // TODO add your handling code here:
        resultsArea.append(ElectionsDemo.region1.getLocation()+"\n"+String.valueOf(ElectionsDemo.region1.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.region2.getLocation()+"\n"+String.valueOf(ElectionsDemo.region2.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.region3.getLocation()+"\n"+String.valueOf(ElectionsDemo.region3.collateResults())+"\n"+"\n");
        resultsArea.append(ElectionsDemo.region4.getLocation()+"\n"+String.valueOf(ElectionsDemo.region4.collateResults())+"\n"+"\n");
    }//GEN-LAST:event_regionalResultsActionPerformed

    private void nationalResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nationalResultsActionPerformed
        // TODO add your handling code here:
        resultsArea.append(ElectionsDemo.national.getLocation()+"\n"+String.valueOf(ElectionsDemo.national.collateResults())+"\n"+"\n");
    }//GEN-LAST:event_nationalResultsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ResultsPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ResultsPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton districtResults;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nationalResults;
    private javax.swing.JButton regionalResults;
    private javax.swing.JTextArea resultsArea;
    private javax.swing.JButton stationResults;
    // End of variables declaration//GEN-END:variables
}
